name: Lint Code Base

on: push

jobs:
  lint:
    name: Run Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
