name: AI Model Testing

on:
  push:
    branches: [ The_Great_Filter ]
  pull_request:
    branches: [ The_Great_Filter ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with xvfb
      run: |
        xvfb-run --server-args="-screen 0 1920x1080x24" python -m pytest
    
    - name: Configure Git, Commit and Push Changes
      if: always() 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./Reports
        git commit -m "Unit Testing Passed"
        git push origin The_Great_Filter
        
